general {
    lock_cmd = pidof hyprlock || hyprlock
    unlock_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 600
    on-timeout = loginctl lock-session  # Lock screen after 10 min
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend  # Suspend after 30 min
    on-resume = hyprctl dispatch dpms on
}

