$shadow_passes = 3
$shadow_size = 5
$shadow_color = rgb(0,0,0)
$shadow_boost = 0,4

animations {
    enabled = true
    bezier = linear, 0, 0, 1, 1
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldWidth, 1, 5, linear
    animation = inputFieldColors, 1, 5, linear
    animation = inputFieldFade, 1, 5, linear
}

general {
    hide_cursor = true
}

background {
    monitor =
    path = /home/z3r0/Pictures/Wallhaven/wallhaven-85pjk1.png
    blur_passes = 1
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor = DP-1
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(00A8E8ff) rgba(007ACCff) rgba(005B9Aff) 45deg
    inner_color = rgba(00000011)
    font_color = rgb(ffffff)
    fade_on_empty = true
    fade_timeout = 0
    font_family = JetBrainsMono Nerd Font
    placeholder_text = password
    hide_input = false
    position = 0, -300
    halign = center
    valign = center
    fail_color = rgb(ff0000)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
}

label {
    monitor = DP-1
    text = Hello, $USER
    color = rgba(255, 255, 255, 1.0)
    font_size = 25
    position = 0, 30
    halign = center
    valign = center
    font_family = Hack Nerd Font
}

label {
    monitor =
    text = cmd[update:1000] echo "$TIME"
    color = rgba(255, 255, 255, 1.0)
    font_size = 156
    position = 0, 400
    halign = center
    valign = center
    font_family = Hack Nerd Font
}

label {
    monitor =
    text = cmd[update:1000] echo "<b> "$(date +'%d %b')" </b>"
    color = rgba(255, 255, 255, 1.0)
    font_size = 56
    position = 0, 250
    halign = center
    valign = center
    font_family = Hack Nerd Font
}


